# Generated by Django 5.2.6 on 2025-09-23 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('atendido', 'Atendido'), ('cancelado', 'Cancelado'), ('ausente', 'Ausente')], default='pendiente', max_length=12)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='pacientes.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='profesionales.profesional')),
            ],
            options={
                'ordering': ['fecha_hora'],
                'indexes': [models.Index(fields=['fecha_hora'], name='turnos_turn_fecha_h_44b454_idx'), models.Index(fields=['estado'], name='turnos_turn_estado_3fab1e_idx')],
                'unique_together': {('profesional', 'fecha_hora')},
            },
        ),
    ]
