# Generated by Django 5.2.6 on 2025-10-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
        ('profesionales', '0001_initial'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='turno',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('profesional', 'fecha_hora'), name='uniq_turno_profesional_fecha'),
        ),
    ]
