# Generated by Django 5.2.6 on 2025-11-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_alter_turno_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(fields=('paciente', 'fecha_hora'), name='uniq_turno_paciente_fecha'),
        ),
    ]
