# Generated by Django 5.2.6 on 2025-10-10 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        ('pacientes', '0002_paciente_alergias_paciente_antecedentes_and_more'),
        ('profesionales', '0002_profesional_centros_profesionalhorario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('anamnesis', models.TextField(blank=True)),
                ('examen_fisico', models.TextField(blank=True)),
                ('diagnostico_codigo', models.CharField(blank=True, max_length=20)),
                ('diagnostico_texto', models.CharField(blank=True, max_length=255)),
                ('estudios_solicitados', models.TextField(blank=True)),
                ('tratamiento', models.TextField(blank=True)),
                ('indicaciones', models.TextField(blank=True)),
                ('proximo_control', models.DateField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='centers.center')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='pacientes.paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones', to='profesionales.profesional')),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='ObservationAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='observaciones/')),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('subido', models.DateTimeField(auto_now_add=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='medical_records.observation')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_json', models.JSONField()),
                ('editado_en', models.DateTimeField(auto_now_add=True)),
                ('editado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='medical_records.observation')),
            ],
            options={
                'ordering': ['-editado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['fecha_hora'], name='medical_rec_fecha_h_a62e52_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['diagnostico_codigo'], name='medical_rec_diagnos_f413af_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['profesional'], name='medical_rec_profesi_413a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['centro'], name='medical_rec_centro__564952_idx'),
        ),
    ]
