# Generated by Django 5.2.6 on 2025-10-31 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_observation_turno_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='observation',
            new_name='medical_rec_turno_i_bb56cc_idx',
            old_name='medical_rec_turno_idx',
        ),
    ]
