# Generated by Django 5.2.6 on 2025-10-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_login_throttle'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginthrottle',
            new_name='usuarios_lo_usernam_c124b0_idx',
            old_name='usuarios_lo_username_9dce2a_idx',
        ),
        migrations.RenameIndex(
            model_name='loginthrottle',
            new_name='usuarios_lo_locked__0643ba_idx',
            old_name='usuarios_lo_locked__9f9f41_idx',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='email_recuperacion',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de recuperación'),
        ),
    ]
