# Generated by Django 5.2.6 on 2025-11-18 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_perfil_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditorialog',
            options={'default_permissions': ('add', 'view'), 'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='exitoso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='metodo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditorialog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='auditorialog',
            name='accion',
            field=models.CharField(choices=[('access', 'Acceso'), ('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('export', 'Exportación'), ('report', 'Reporte'), ('login', 'Login'), ('logout', 'Logout')], max_length=12),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['usuario', 'fecha'], name='usuarios_au_usuario_ae7ad2_idx'),
        ),
    ]
