# Generated by Django 5.2.6 on 2025-10-10 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '__first__'),
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='centros',
            field=models.ManyToManyField(blank=True, related_name='profesionales', to='centers.center'),
        ),
        migrations.CreateModel(
            name='ProfesionalHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='centers.center')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='profesionales.profesional')),
            ],
            options={
                'ordering': ['profesional', 'centro', 'dia_semana', 'hora_inicio'],
                'unique_together': {('profesional', 'centro', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
