# Generated by Django 5.2.6 on 2025-11-04 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0003_especialidad_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesionales', to='profesionales.especialidad'),
        ),
    ]
