# Generated by Django 5.2.6 on 2025-10-31 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_profesionales_asignados'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='obra_social_legacy',
            field=models.CharField(blank=True, db_column='obra_social', default='', editable=False, max_length=50),
        ),
    ]
