# Generated by Django 5.2.6 on 2025-10-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_paciente_alergias_paciente_antecedentes_and_more'),
        ('profesionales', '0002_profesional_centros_profesionalhorario'),
        ('turnos', '0002_alter_turno_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='pacientes.paciente')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='profesionales.profesional')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificaciones', to='turnos.turno')),
            ],
            options={
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='feedback_sa_fecha_9fbacb_idx'), models.Index(fields=['puntaje'], name='feedback_sa_puntaje_205b50_idx')],
            },
        ),
    ]
