# Generated by Django 5.2.6 on 2025-10-10 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('historia_completa', 'Historia Clínica Completa'), ('observacion', 'Informe de Observación'), ('epicrisis', 'Epicrisis / Resumen'), ('certificado', 'Certificado Médico'), ('estadistico', 'Estadístico'), ('administrativo', 'Administrativo')], max_length=30)),
                ('template_path', models.CharField(max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], max_length=10)),
                ('activo', models.BooleanField(default=False)),
                ('proximas_ejecuciones', models.IntegerField(default=0)),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True)),
                ('destinatarios', models.TextField(blank=True, help_text='Lista de emails separados por coma')),
                ('parametros_json', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('parametros_json', models.JSONField(default=dict)),
                ('archivo_pdf', models.FileField(upload_to='reportes/')),
                ('centro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centers.center')),
                ('usuario_generador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
