# Generated by Django 5.2.6 on 2025-10-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='obrasocial',
            index=models.Index(fields=['activo'], name='obras_obras_activo_33dc19_idx'),
        ),
        migrations.AddIndex(
            model_name='obrasocial',
            index=models.Index(fields=['nombre'], name='obras_obras_nombre_73b922_idx'),
        ),
    ]
