# Generated by Django 5.2.6 on 2025-10-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_alter_center_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
