# Generated by Django 5.2.6 on 2025-10-31 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0004_holiday'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='holiday',
            new_name='centers_hol_fecha_bdd2f3_idx',
            old_name='centers_hol_fecha_idx',
        ),
    ]
